import Foundation
import SwiftUI

// MARK: - Localization (EN / FR)

enum L10n {
    /// Translation by key — reads "appLanguage" from UserDefaults ("en" | "fr")
    static func t(_ key: String) -> String {
        let lang = UserDefaults.standard.string(forKey: "appLanguage") ?? "en"
        if lang == "fr", let fr = stringsFR[key] { return fr }
        return strings[key] ?? key
    }

    // MARK: - English Strings

    private static let strings: [String: String] = [

        // General
        "save":                 "Save",
        "done":                 "Done",
        "cancel":               "Cancel",
        "delete":               "Delete",
        "loading":              "Loading...",
        "error":                "Error",
        "offline":              "No connection",
        "golden_rule":          "under 3h per day",
        "password_hint":        "6 characters minimum",
        "welcome_empty_title":  "Challenge your friends",
        "welcome_empty_desc":   "Create a group and invite your friends\nto see who can spend the least time on their phone.",

        // Onboarding walkthrough
        "skip":                 "skip",
        "ob_time_title":        "Your time is precious",
        "ob_time_desc":         "The average person spends\n4 hours a day on their phone.\nThat's 60 full days per year.",
        "ob_friends_title":     "Do it with friends",
        "ob_friends_desc":      "Create a group, invite your friends,\nand see who can spend\nthe least time on their phone.",
        "ob_challenge_title":   "Challenge each other",
        "ob_challenge_desc":    "Competitive or collective mode.\nThe loser buys a round.\nStay under your goal to win.",
        "ob_track_title":       "100% automatic",
        "ob_track_desc":        "PAKT reads your screen time\nautomatically. No manual input.\nYour data stays private.",

        // Onboarding
        "get_started":          "get started",
        "tagline":              "A pakt between friends\nthat could change your life.",
        "already_account":      "I already have an account",
        "data_privacy":         "Your data is only shared\nwith your group members.",
        "create_account":       "Create account",
        "welcome_back":         "Welcome back",
        "sign_in":              "Sign in",
        "sign_in_instead":      "Sign in instead",
        "create_instead":       "Create account",
        "first_name":           "First name",
        "email":                "Email",
        "password":             "Password",
        "continue":             "Continue",
        "or":                   "or",
        "username_taken":       "this username is already taken",
        "accept_terms_prefix":  "I accept the ",
        "terms_of_use":         "Terms of Use",
        "accept_terms_and":     " and the ",

        // Permissions
        "screen_time_access":   "Screen time access",
        "screen_time_desc":     "PAKT reads your screen time automatically\nso you don't have to enter it manually.\nonly your groups can see it.",
        "total_time_day":       "total time per day — automatic",
        "history_7_30":         "7 and 30 day history",
        "no_app_names":         "we never see which apps you use",
        "group_only":           "visible only to your group",
        "allow_access":         "allow access",
        "enter_manually":       "Enter manually instead",
        "perm_denied":          "permission denied — you can enable it later in Settings",

        // Today
        "yesterday":            "yesterday",
        "goal_reached":         "goal reached",
        "goal_not_reached":     "goal not reached",
        "over_goal":            "over goal",
        "under_goal":           "under goal",
        "no_data_yet":          "No data yet",
        "day_streak":           "day streak",
        "under_goal_streak":    "under your daily goal",
        "my_challenges":        "my challenges",

        // Profile
        "friends":              "Friends",
        "enter_score":          "enter yesterday's screen time",
        "update_score":         "update yesterday's score",
        "synced_auto":          "screen time synced automatically",
        "waking_day":           "of your waking day",
        "waking_day_screens":   "of your waking day on screens",
        "under_goal_keep":      "under your goal — keep it up",
        "days_wasted":          "full days wasted per year at this pace",
        "week_avg":             "week avg",
        "month_avg":            "month avg",
        "active_challenges":    "my active challenges",
        "no_challenges":        "No active challenges",
        "days_remaining":       "days remaining",
        "last_day":             "last day",
        "rank":                 "rank",
        "you":                  "you",

        // Groups
        "groups":               "Groups",
        "create_group":         "Create a group",
        "join_group":           "Join a group",
        "enter_code":           "Enter group code",
        "join":                 "Join",
        "group_name":           "Group name",
        "competitive":          "Competitive",
        "collective":           "Collective",
        "comp_desc":            "lowest screen time wins",
        "coll_desc":            "group average must meet goal",
        "daily_goal":           "Daily goal",
        "duration":             "duration",
        "1_day":                "1 day",
        "1_week":               "1 week",
        "2_weeks":              "2 weeks",
        "1_month":              "1 month",
        "members":              "members",
        "leave_group":          "Leave group",
        "share_code":           "Share code",

        // Daily score
        "yesterdays_st":        "yesterday's screen time",
        "auto_tracking_on":     "automatic tracking is on — use this for manual override",
        "check_settings":       "Settings → Screen Time → scroll to Yesterday",
        "goal_done":            "goal reached — well done",
        "goal_not_done":        "goal not reached this time",
        "full_days_year":       "full days per year",

        // Settings
        "settings":             "Settings",
        "daily_st_goal":        "DAILY SCREEN TIME GOAL",
        "waking_pct":           "of your waking day",
        "save_goal":            "Save goal",
        "saved":                "Saved",
        "appearance":           "APPEARANCE",
        "dark_mode":            "Dark mode",
        "language":             "Language",
        "username":             "USERNAME",
        "account":              "ACCOUNT",
        "sign_out":             "Sign out",
        "available":            "available",
        "already_taken":        "already taken",
        "checking":             "checking...",

        // Settings (extended)
        "profile":              "Profile",
        "preferences":          "PREFERENCES",
        "support":              "SUPPORT",
        "edit_photo":           "edit photo",
        "screen_time_status":   "screen time",
        "connected":            "connected",
        "not_connected":        "not connected",
        "open_screen_time_settings": "Open Screen Time settings",
        "privacy_policy":       "Privacy policy",
        "help_feedback":        "Help & feedback",
        "version":              "version",
        "delete_account":       "Delete account",
        "delete_account_warn":  "This will permanently delete your account and all your data. This action cannot be undone.",
        "confirm_delete":       "yes, delete everything",
        "pause_account":        "pause my account",
        "confirm_password":     "confirm your password",
        "reenter_password_desc": "Enter your password to permanently delete your account.",

        // Friends
        "incoming_requests":    "incoming requests",
        "my_friends":           "my friends",
        "search_friends":       "search friends",
        "add_friend":           "add friend",
        "remove":               "Remove",
        "accept":               "Accept",
        "decline":              "Decline",

        // Notifications
        "notifications":        "Notifications",
        "group_invite":         "invited you to join",

        // Scope
        "scope_total":          "total screen time",
        "scope_total_desc":     "ranking based on total daily screen time",
        "scope_social":         "social media only",
        "scope_social_desc":    "ranking based on social media time only — Instagram, TikTok, etc.",

        // Categories
        "social":               "social",
        "on_social_media":      "on social media",
        "social_goal":          "SOCIAL MEDIA GOAL",
        "utilities":            "utilities",
        "entertainment":        "entertainment",
        "other":                "other",

        // Activities
        "instead_of_scrolling": "INSTEAD OF SCROLLING",
        "all":                  "all",
        "cat_outdoor":          "outdoor",
        "cat_food":             "food",
        "cat_creative":         "creative",
        "cat_sport":            "sport",
        "cat_chill":            "chill",
        "cat_social":           "social",

        // Activities
        "activities_title":     "Messages",
        "activities_subtitle":  "Find a mate to stop scrolling",
        "tab_friends":          "Friends",
        "tab_near_you":         "Near you",
        "near_you_title":       "Instead of scrolling",
        "near_you_coming":      "Coming soon",
        "near_you_desc":        "Activities from local spots\nnear you — cafés, gyms, parks...",
        "spots":                "Spots",
        "free_activities":      "Free",
        "visit_website":        "Website",
        "go_with_friend":       "Go with a friend",
        "no_venues_radius":     "No spots in this radius",
        "allow_location":       "Enable location",
        "location_needed":      "To see what's near you",
        "chat_expires":         "This chat resets in 24h",
        "member_since":         "Member since",
        "propose_activity":     "PROPOSE AN ACTIVITY",
        "incoming_proposals":   "INCOMING",
        "sent_proposals":       "SENT",
        "proposal_sent":        "Proposal sent",
        "send_proposal":        "Send",
        "no_conversations_yet": "No conversations yet",
        "start_conversation":   "New conversation",
        "send_first_activity":  "Send an activity to get started",
        "propose_activity_short": "Propose an activity",
        "type_message":         "Message...",
        "proposal_mine":        "How about {activity}?",
        "proposal_theirs":      "Wants to {activity}",
        "proposal_mine_short":  "Want to do this together?",
        "proposal_theirs_short": "wants to do this with you",
        "resp_lets_go":         "Let's go!",
        "resp_cant_now":        "Can't rn",
        "resp_rather_scroll":   "I'd rather scroll",
        "accepted":             "accepted",
        "no_friends_yet":       "No friends yet",
        "add_friends_first":    "Add friends to propose activities",
        "act_walk":             "Walk",
        "act_run":              "Run",
        "act_hike":             "Hike",
        "act_bike":             "Bike ride",
        "act_gym":              "Gym",
        "act_tennis":           "Tennis",
        "act_basketball":       "Basketball",
        "act_swim":             "Swim",
        "act_coffee":           "Coffee",
        "act_brunch":           "Brunch",
        "act_cook":             "Cook",
        "act_dinner":           "Dinner",
        "act_board_game":       "Board game",
        "act_read":             "Read",
        "act_draw":             "Draw",
        "act_music":            "Music",
        "act_park":             "Park",
        "act_picnic":           "Picnic",
        "act_movie":            "Movie",
        "act_sunset":           "Sunset",

        // Create group
        "new_group":            "New group",
        "group_name_label":     "GROUP NAME",
        "game_mode":            "GAME MODE",
        "tracked_time":         "TRACKED TIME",
        "per_day_max":          "per day maximum",
        "waking_day_pct":       "of a 16h waking day",
        "group_created":        "group created",
        "invite_code":          "INVITE CODE",
        "copy_code":            "copy code",
        "view_my_group":        "view my group",
        "comp_desc_long":       "ranking — the worst performer buys a round",
        "coll_desc_long":       "together — the group average must stay on target",
        "comp_goal_desc":       "everyone must stay under — the ranking determines the loser",
        "coll_goal_desc":       "the group average must stay under this limit",
        "challenge_duration":   "challenge duration",
        "create_group_btn":     "Create group",
        "mode_label":           "mode",
        "tracked_label":        "tracked",
        "days_count":           "days",

        // Join group
        "group_code":           "Group code",
        "searching":            "Searching...",
        "joined_group":         "you joined the group",
        "already_in":           "you're already in this group",
        "group_not_found":      "no group found with this code",
        "something_wrong":      "something went wrong",
        "lets_go":              "let's go",

        // Group detail
        "final_ranking":        "final ranking",
        "final_ranking_desc":   "This ranking determines the winner at the end of the challenge",
        "time_spent":           "total time",
        "this_week":            "THIS WEEK",
        "overview":             "OVERVIEW",
        "group_avg":            "GROUP AVG",
        "best":                 "BEST",
        "under_goal_label":     "UNDER GOAL",
        "comparison":           "COMPARISON",
        "over_goal_label":      "over goal",
        "progress":             "PROGRESS",
        "completed":            "completed",
        "pct_waking":           "of your waking day",

        // Stats dashboard
        "group_avg_today":      "Group avg today",
        "hours_saved":          "Hours saved",
        "success_rate":         "Success rate",
        "awards":               "AWARDS",
        "most_improved":        "MOST IMPROVED",
        "most_consistent":      "MOST CONSISTENT",
        "best_single_day":      "BEST SINGLE DAY",
        "worst_single_day":     "WORST SINGLE DAY",
        "closest_to_goal":      "CLOSEST TO GOAL",

        // Edit group
        "edit_group":           "Edit group",
        "challenge_settings":   "CHALLENGE SETTINGS",
        "settings_locked":      "challenge settings cannot be changed once started",
        "group_code_label":     "GROUP CODE",
        "copied":               "copied!",
        "copy":                 "copy",
        "share_code_desc":      "share this code so friends can join",
        "invite_friends":       "INVITE FRIENDS",
        "invited_check":        "invited ✓",
        "invite_btn":           "invite",
        "cancel_invite":        "cancel",
        "delete_group":         "delete group",
        "delete_group_warn":    "This will permanently remove the group for all members.",
        "leave_group_warn":     "You'll be removed from the group. Other members won't be affected.",
        "save_changes":         "save changes",

        // Friends
        "friends_title":        "Friends",
        "friends_subtitle":     "Add friends to challenge them",
        "friend_requests":      "friend requests",
        "wants_friend":         "wants to be your friend",
        "no_friends":           "No friends yet — search by username below",
        "find_username":        "find by username",
        "username_ph":          "username...",
        "no_user_found":        "No user found",
        "from_contacts":        "from your contacts",
        "no_contacts":          "None of your contacts are on PAKT yet",
        "find_contacts":        "find friends from contacts",
        "invite_friend":        "invite a friend",
        "copy_invite":          "copy invite link",
        "share_via":            "share via iMessage, WhatsApp...",
        "friends_check":        "friends ✓",
        "request_sent":         "request sent",
        "add_friend_btn":       "add friend",

        // Notifications
        "group_invitations":    "group invitations",
        "no_notifs":            "No notifications",
        "no_notifs_desc":       "When a friend invites you to a group,\nyou'll see it here.",
        "invited_to_group":     "invited you to join a group",
        "join_group_btn":       "join group",
        "just_now":             "just now",

        // Member profile
        "no_data_today":        "No data today",
        "waking_screens_avg":   "of waking day on screens (final avg)",
        "days_lost_year":       "full days lost per year at this rate",
        "years_in_lifetime":    "years of a lifetime (80y)",
        "today_label":          "TODAY",
        "since_start":          "FINAL",
        "group_goal":           "GROUP GOAL",
        "per_day_max_label":    "per day maximum",
        "days_under":           "days under goal",
        "days_over":            "days over goal",
        "today_excluded":       "today excluded",
        "avg_since_start":      "final average",

        // Challenge result
        "challenge_complete":   "challenge complete",
        "challenge_failed":     "challenge failed",
        "wins_challenge":       "wins the challenge",
        "whats_next":           "WHAT'S NEXT",
        "restart_same":         "restart same challenge",
        "new_challenge_started": "new challenge started",
        "start":                "start",
        "name_new_challenge":   "name the new challenge",

        // Username
        "choose_username":      "Choose your name",
        "choose_username_desc": "This is how your friends will see you.\nIt must be unique.",

        // Email verification
        "verify_email":         "Verify your email",
        "verify_email_desc":    "We sent a 6-digit code to your email.\nEnter it below to verify your account.",
        "i_verified":           "I've verified my email",
        "resend_email":         "Resend code",
        "email_not_verified":   "Invalid or expired code",
        "today":                "today",

        // Medals
        "medals":               "MEDALS",
        "rules":                "RULES",
        "rules_desc":           "The player with the lowest screen time at the end of the challenge wins a medal.",

        // Chart
        "day":                  "Day",
        "week":                 "Week",
        "month":                "Month",
        "goal":                 "goal",

        // Period
        "period_final":         "Final",
        "period_day":           "Day",

        // Streak
        "streak_explanation":   "stay under 3h to earn streaks",
        "streak_explanation_long": "Stay under the limit for several consecutive days to start a streak. The longer your streak, the better.",

        // Misc
        "per_day":              "/day",
        "members_count":        "members",
        "days_left":            "days left",

        // Stakes
        "stake_title":              "What's at stake?",
        "stake_label":              "STAKE",
        "stake_for_fun":            "For fun",
        "stake_last_pays":          "Last pays a round",
        "stake_dinner":             "Dinner",
        "stake_custom":             "Custom",
        "stake_custom_placeholder": "Write your stake...",

        // Required players
        "required_players_title":   "How many players?",
        "required_players":         "required players",
        "players_needed":           "players to start",
        "players_needed_desc":      "The pakt starts when this many\npeople have signed — including you",

        // Pakt status
        "status_pending":           "pending",
        "status_active":            "active",
        "pending_pakts":            "WAITING FOR SIGNATURES",
        "active_pakts":             "ACTIVE PAKTS",
        "finished_pakts":           "FINISHED",
        "delete_pakt":              "Delete pakt",
        "signatures":               "signatures",
        "waiting_signatures":       "Waiting for signatures",
        "waiting_signature":        "waiting...",
        "signatures_needed_desc":   "Share the code with your friends.\nThe pakt starts as soon as everyone signs.",
        "pakt_created":             "Pakt created",
        "pakt_activated":           "The pakt has started!",
        "sign_the_pakt":            "Sign the pakt",

        // Empty states
        "search_or_invite":         "Search by username or invite a friend",
        "all_caught_up":            "You're all caught up!",
        "pending_invitations":      "pending invitations",

        // Group chat
        "sent":                     "Sent",
        "no_messages_yet":          "No messages yet",

        // Invite
        "invite_message":           "Join me on PAKT! Download the app and use my group code:",

        // Group list / detail
        "starts_midnight":          "Starts at midnight",
        "challenge_begins_midnight": "The challenge will begin at 00:00.\nEveryone's score starts fresh tomorrow.",

        // Context menus
        "archive":                  "Archive",
        "unarchive":                "Unarchive",
        "delete_for_me":            "Delete for me",
        "delete_for_everyone":      "Delete for everyone",

        // Activities
        "no_archived_conversations": "No archived conversations",

        // Members
        "see_all":                  "See all",
        "admin":                    "Admin",

        // Create group
        "start_now":                "Start now",
        "start_time":               "START TIME",
        "at_midnight":              "At 00:00",

        // Charts
        "details":                  "details",

        // Challenge result slides
        "the_winner":               "THE WINNER",
        "avg_per_day":              "average per day",
        "goal_reached_title":       "GOAL\nREACHED",
        "goal_not_reached_title":   "GOAL\nNOT REACHED",
        "group_crushed_it":         "Your group crushed it.",
        "better_luck":              "Better luck next time.",
        "final_ranking_title":      "FINAL RANKING",
        "best_day":                 "BEST DAY",
        "least_st_day":             "Least screen time\nin a single day",
        "screen_time_label":        "screen time",
        "no_data_recorded":         "No data recorded",
        "worst_day":                "WORST DAY",
        "most_st_day":              "Most screen time\nin a single day",
        "your_group":               "YOUR GROUP",
        "in_numbers":               "in numbers",
        "players":                  "PLAYERS",
        "days_label":               "DAYS",
        "daily_goal_label":         "DAILY GOAL",
        "group_average":            "GROUP AVERAGE",
        "ready_another":            "READY FOR\nANOTHER ONE?",
        "same_group_new":           "Same group, new challenge.",
        "restart_challenge":        "Restart same challenge",
        "harder_goal":              "Harder goal",
        "swipe_to_explore":         "Swipe to explore",
        "new_challenge_btn":        "Start",
        "name_challenge":           "Name the new challenge",

        // Group card competition
        "you_lead":                 "You lead!",
        "leads":                    "leads",
        "home":                     "Home",
        "friends_section":          "Friends",
        "search_placeholder":       "Search groups & friends",
        "ranking_tab":              "Ranking",
        "data_tab":                 "Data",
        "stats_tab":                "Stats",
        "messages_tab":             "Messages",
        "profile_tab":              "Profile",

        // Events
        "create_event":             "Create event",
        "no_events_yet":            "No events yet.\nCreate one and invite friends!",
        "event_title":              "TITLE",
        "event_title_placeholder":  "What's the plan?",
        "event_description":        "DESCRIPTION",
        "event_desc_placeholder":   "Tell people more about it...",
        "event_location":           "LOCATION",
        "event_location_placeholder": "Where?",
        "event_date":               "DATE & TIME",
        "going":                    "Going",
        "interested":               "Interested",
        "invite":                   "Invite",
        "invited":                  "Invited",
        "created_by":               "by",
        "events_attending":         "EVENTS",
        "public_event":             "Public",
        "friends_only":             "Friends only",
        "open_maps":                "Open in Google Maps",
        "add_to_calendar":          "Add to calendar",
        "added_to_calendar":        "Added",
        "edit_event":               "Edit event",
        "add_photo":                "Add a photo",
        "change_photo":             "Change photo",
        "visibility":               "VISIBILITY",
        "ranking_final":            "FINAL RANKING",
        "ranking_today":            "TODAY",

        // NearYouView / Events
        "retry":                    "Retry",
        "refresh":                  "Refresh",
        "no_events_nearby":         "No events found nearby",
        "nearby_events":            "Nearby Events",
        "see_event":                "See Event",
        "share_event":              "Share Event",
        "add_message":              "Add a message...",
        "view_details":             "View details",
        "website":                  "Website",
        "instagram_short":          "ig",
        "venue_label":              "VENUE",
        "about":                    "About",
        "please_note":              "Please note",
        "get_tickets":              "Get Tickets",
        "group_code_placeholder":   "GRP-XXXX",
        "delete_event":             "Delete this event?",
        "veteran":                  "Member since",
        "events":                   "Events",
        "leading_groups":           "#1 in %d groups",
        "on_phone_today":           "on your phone today. Here's what to do instead.",

        // Report
        "report":                   "Report",
        "report_message":           "Report this message?",
        "report_inappropriate":     "Inappropriate content",
        "report_spam":              "Spam",
        "block_user":               "Block user",

        // Onboarding — first group step
        "ob_group_title":           "Join a group",
        "ob_group_desc":            "Create or join your first group\nto start competing with friends!",
        "ob_create_group":          "Create a group",
        "ob_join_code":             "Join with a code",
        "ob_skip_for_now":          "Skip for now",

        // Brussels events
        "brussels_agenda":          "BRUSSELS AGENDA",
        "powered_by_brussels":      "Powered by agenda.brussels",

    ]

    // MARK: - French Strings

    private static let stringsFR: [String: String] = [
        "save": "Enregistrer", "done": "Terminé", "cancel": "Annuler", "delete": "Supprimer",
        "loading": "Chargement...", "error": "Erreur", "offline": "Pas de connexion",
        "golden_rule": "moins de 3h par jour", "password_hint": "6 caractères minimum",
        "welcome_empty_title": "Défie tes amis", "welcome_empty_desc": "Crée un groupe et invite tes amis\npour voir qui passe le moins de temps sur son tel.",
        "skip": "passer",
        "ob_time_title": "Ton temps est précieux", "ob_time_desc": "En moyenne, on passe\n4 heures par jour sur son tel.\nSoit 60 jours par an.",
        "ob_friends_title": "Fais-le avec tes amis", "ob_friends_desc": "Crée un groupe, invite tes amis,\net vois qui passe\nle moins de temps sur son tel.",
        "ob_challenge_title": "Défiez-vous", "ob_challenge_desc": "Mode compétitif ou collectif.\nLe dernier paye sa tournée.\nReste sous ton objectif pour gagner.",
        "ob_track_title": "100% automatique", "ob_track_desc": "PAKT lit ton temps d'écran\nautomatiquement. Rien à saisir.\nTes données restent privées.",
        "today": "aujourd'hui", "yesterday": "hier", "just_now": "à l'instant",
        "home": "Accueil", "groups": "Groupes", "friends_section": "Amis",
        "search_placeholder": "Rechercher groupes et amis",
        "create_group": "Créer un groupe", "join_group": "Rejoindre un groupe",
        "group_code": "CODE DU GROUPE", "group_code_placeholder": "GRP-XXXX",
        "searching": "Recherche...", "join": "Rejoindre",
        "already_in": "Tu es déjà dans ce groupe", "group_not_found": "Groupe introuvable", "something_wrong": "Un problème est survenu",
        "joined_group": "Tu as rejoint le groupe", "lets_go": "C'est parti",
        "pending_pakts": "EN ATTENTE DE SIGNATURES", "active_pakts": "PAKTS ACTIFS", "finished_pakts": "TERMINÉS",
        "delete_pakt": "Supprimer le pakt", "leave_group": "Quitter le groupe",
        "signatures": "signatures", "waiting_signatures": "En attente de signatures",
        "waiting_signature": "en attente...",
        "signatures_needed_desc": "Partage le code avec tes amis.\nLe pakt démarre quand tout le monde a signé.",
        "pakt_created": "Pakt créé", "pakt_activated": "Le pakt a commencé !",
        "sign_the_pakt": "Signer le pakt",
        "status_pending": "en attente", "status_active": "actif",
        "starts_midnight": "Commence à minuit",
        "challenge_begins_midnight": "Le défi commence à 00h00.\nLes scores repartent de zéro demain.",
        "ranking_tab": "Classement", "stats_tab": "Stats", "messages_tab": "Messages", "profile_tab": "Profil",
        "ranking_final": "CLASSEMENT FINAL", "ranking_today": "AUJOURD'HUI",
        "you_lead": "Tu mènes !", "leads": "mène",
        "competitive": "Compétitif", "collective": "Collectif",
        "1_day": "1 jour", "1_week": "1 semaine", "2_weeks": "2 semaines", "1_month": "1 mois",
        "scope_total": "TOTAL", "social": "SOCIAL",
        "period_final": "Final", "period_day": "Jour",
        "goal": "objectif", "progress": "PROGRESSION",
        "days_remaining": "jours restants", "last_day": "dernier jour",
        "best": "MEILLEUR", "under_goal_label": "SOUS L'OBJECTIF", "over_goal_label": "au-dessus",
        "under_goal": "sous l'objectif",
        "rules": "RÈGLES", "rules_desc": "Le joueur avec le moins de temps d'écran à la fin du défi gagne une médaille.",
        "per_day": "/jour", "members_count": "membres", "days_left": "jours restants",
        "stake_title": "Quel est l'enjeu ?", "stake_label": "ENJEU",
        "stake_for_fun": "Pour le fun", "stake_last_pays": "Le dernier paye sa tournée",
        "stake_dinner": "Dîner", "stake_custom": "Personnalisé", "stake_custom_placeholder": "Écris ton enjeu...",
        "required_players_title": "Combien de joueurs ?", "required_players": "joueurs requis",
        "players_needed": "joueurs pour commencer",
        "players_needed_desc": "Le pakt démarre quand ce nombre\nde personnes ont signé — toi inclus",
        "invite_code": "CODE D'INVITATION", "copy_code": "Copier",
        "invite_friends": "INVITER DES AMIS", "invite_btn": "inviter",
        "invite_message": "Rejoins-moi sur PAKT ! Télécharge l'app et utilise mon code de groupe :",
        "no_friends": "Pas encore d'amis",
        "challenge_complete": "défi terminé", "challenge_failed": "défi échoué",
        "wins_challenge": "remporte le défi",
        "the_winner": "LE GAGNANT", "avg_per_day": "moyenne par jour",
        "final_ranking_title": "CLASSEMENT FINAL",
        "best_day": "MEILLEUR JOUR", "least_st_day": "Le moins de temps d'écran\nen une journée",
        "worst_day": "PIRE JOUR", "most_st_day": "Le plus de temps d'écran\nen une journée",
        "screen_time_label": "temps d'écran", "no_data_recorded": "Aucune donnée enregistrée",
        "your_group": "VOTRE GROUPE", "in_numbers": "en chiffres",
        "players": "JOUEURS", "days_label": "JOURS", "daily_goal_label": "OBJECTIF QUOTIDIEN",
        "group_average": "MOYENNE DU GROUPE",
        "ready_another": "PRÊT POUR\nUN AUTRE ?", "same_group_new": "Même groupe, nouveau défi.",
        "restart_challenge": "Relancer le même défi", "harder_goal": "Objectif plus dur",
        "swipe_to_explore": "Swipe pour explorer",
        "whats_next": "ET MAINTENANT", "start": "démarrer",
        "new_challenge_started": "nouveau défi lancé", "name_challenge": "Nom du nouveau défi",
        "choose_username": "Choisis ton nom", "choose_username_desc": "C'est comme ça que tes amis te verront.\nIl doit être unique.",
        "verify_email": "Vérifie ton email", "verify_email_desc": "On a envoyé un code à 6 chiffres à ton email.\nEntre-le ci-dessous.",
        "i_verified": "J'ai vérifié mon email", "resend_email": "Renvoyer le code", "email_not_verified": "Code invalide ou expiré",
        "medals": "MÉDAILLES",
        "day": "Jour", "week": "Semaine", "month": "Mois",
        "streak_explanation": "reste sous 3h pour gagner des streaks",
        "streak_explanation_long": "Reste sous la limite plusieurs jours d'affilée pour lancer un streak. Plus c'est long, mieux c'est.",
        "day_streak": "jours de streak",
        "sent": "Envoyé", "no_messages_yet": "Pas encore de messages",
        "type_message": "Message...", "copy": "Copier",
        "search_or_invite": "Chercher par pseudo ou inviter un ami",
        "all_caught_up": "T'es à jour !", "pending_invitations": "invitations en attente",
        "group_invitations": "invitations de groupe", "no_notifs": "Pas de notifications",
        "no_notifs_desc": "Quand un ami t'invite dans un groupe,\ntu le verras ici.",
        "invited_to_group": "t'a invité à rejoindre un groupe", "join_group_btn": "rejoindre",
        "archive": "Archiver", "unarchive": "Désarchiver",
        "delete_for_me": "Supprimer pour moi", "delete_for_everyone": "Supprimer pour tous",
        "no_archived_conversations": "Pas de conversations archivées",
        "see_all": "Tout voir", "admin": "Admin",
        "start_now": "Commencer", "start_time": "DÉBUT", "at_midnight": "À 00h00",
        "details": "détails",
        "no_data_today": "Pas de données aujourd'hui",
        "waking_screens_avg": "du temps éveillé sur les écrans (moy. finale)",
        "days_lost_year": "jours perdus par an à ce rythme",
        "years_in_lifetime": "ans d'une vie (80 ans)",
        "today_label": "AUJOURD'HUI", "since_start": "FINAL",
        "group_goal": "OBJECTIF DU GROUPE", "per_day_max_label": "par jour maximum",
        "days_under": "jours sous l'objectif", "days_over": "jours au-dessus",
        "today_excluded": "aujourd'hui exclu", "avg_since_start": "moyenne finale",
        "you": "toi",
        "resp_lets_go": "Let's go !", "resp_cant_now": "Pas dispo", "resp_rather_scroll": "Je scroll",
        "goal_reached_title": "OBJECTIF\nATTEINT", "goal_not_reached_title": "OBJECTIF\nNON ATTEINT",
        "group_crushed_it": "Votre groupe a tout déchiré.", "better_luck": "La prochaine sera la bonne.",
        "near_you_title": "Plutôt que scroller",
        "no_challenges": "Pas de défis",
        "on_social_media": "sur les réseaux",
        "add_friend": "Ajouter un ami",
        "create_event": "Créer un événement", "edit_event": "Modifier l'événement",
        "no_events_yet": "Pas encore d'événements.\nCrée-en un et invite tes amis !",
        "event_title": "TITRE", "event_title_placeholder": "C'est quoi le plan ?",
        "event_description": "DESCRIPTION", "event_desc_placeholder": "Dis-en plus...",
        "event_location": "LIEU", "event_location_placeholder": "Où ?",
        "event_date": "DATE ET HEURE",
        "going": "J'y vais", "interested": "Intéressé",
        "invite": "Inviter", "invited": "Invité",
        "created_by": "par", "events_attending": "ÉVÉNEMENTS",
        "public_event": "Public", "friends_only": "Amis uniquement",
        "open_maps": "Ouvrir dans Google Maps",
        "add_to_calendar": "Ajouter au calendrier", "added_to_calendar": "Ajouté",
        "invite_friends": "Inviter des amis",
        "add_photo": "Ajouter une photo", "change_photo": "Changer la photo",
        "visibility": "VISIBILITÉ",
        "retry": "Réessayer", "refresh": "Actualiser",
        "no_events_nearby": "Pas d'événements à proximité",
        "nearby_events": "Événements à proximité", "see_event": "Voir l'événement",
        "share_event": "Partager l'événement",
        "add_message": "Ajouter un message...",
        "view_details": "Voir les détails", "website": "Site web", "instagram_short": "ig",
        "venue_label": "LIEU", "about": "À propos", "please_note": "À noter",
        "get_tickets": "Obtenir des billets",
        "delete_event": "Supprimer cet événement ?",
        "veteran": "Membre depuis", "events": "Événements",
        "leading_groups": "#1 dans %d groupes",
        "on_phone_today": "sur ton tel aujourd'hui. Voilà quoi faire à la place.",
        "report": "Signaler", "report_message": "Signaler ce message ?",
        "report_inappropriate": "Contenu inapproprié", "report_spam": "Spam", "block_user": "Bloquer",
        "ob_group_title": "Rejoins un groupe",
        "ob_group_desc": "Crée ou rejoins ton premier groupe\npour commencer à défier tes amis !",
        "ob_create_group": "Créer un groupe", "ob_join_code": "Rejoindre avec un code",
        "ob_skip_for_now": "Passer pour l'instant",
        "stats_tab": "Stats",
        "group_avg_today": "Moy. groupe aujourd'hui", "hours_saved": "Heures économisées",
        "success_rate": "Taux de réussite", "awards": "DISTINCTIONS",
        "most_improved": "PLUS AMÉLIORÉ", "most_consistent": "PLUS RÉGULIER",
        "best_single_day": "MEILLEUR JOUR", "worst_single_day": "PIRE JOUR",
        "closest_to_goal": "PLUS PROCHE DE L'OBJECTIF",
        "brussels_agenda": "AGENDA BRUXELLES",
        "powered_by_brussels": "Source: agenda.brussels",
    ]
}
